### ISSUE TITLE
Edits to citations

### ISSUE THREAD

**Issue by afilazzola** [cjlortie/Strategic_retired_lands_synthesis#11]
Bean citation twice. 
Clark et al. 2005 citation needs to be revised: Clark, H. O., Warrick, G. D., Cypher, B. L., Kelly, P. A., Williams, D. F., & Grubbs, D. E. (2005). Competitive interactions between endangered kit foxes and nonnative red foxes. Western North American Naturalist, 153-163.
All caps
Cortina & Vallejo 1998 citation needs to be lower case. 
Filazzola citation twice
Coding syntax carried into citation for Grimes et al. 2014 citation.  (i.e. <i>Gambelia sila</i>)
Groot paper no longer in press: 8(1), 706-715.
McKinney et al. 2014 has a number in the Journal “Restoration Ecology”
Nguyen et al. 2015. Needs journal: “Journal of Water and Climate Change”
Noble citation three times
Pearson et al. 2007. “Original article” in journal title.
Warrick & Cypher 1998 citation needs to be replaced: Warrick, G. D., & Cypher, B. L. (1998). Factors affecting the spatial distribution of San Joaquin kit foxes. The Journal of wildlife management, 707-717.
Zoellick et al. 2002 citation needs to be revised: Zoellick, B. W., Harris, C. E., Kelly, B. T., O'Farrell, T. P., Kato, T. T., & Koopman, M. E. (2002). Movements and home ranges of San Joaquin kit foxes (Vulpes macrotis mutica) relative to oil-field development. Western North American Naturalist, 151-159.
Stylinski et al. 1998 citation twice. 

Citations to add:

Hanak, E., Lund, J., Arnold, B., Escriva-Bou, A., Gray, B., Green, S., ... & Moyle, P. (2017). Water Stress and a Changing San Joaquin Valley. Public Policy Institute of California.
Butterfield, H.S., R. Kelsey, A. Hart, T. Biswas, M. Kramer, D. Cameron, L. Crane, and E. Brand. 2017. Identification of potentially suitable habitat for strategic land retirement and restoration in the San Joaquin Desert. Unpublished report. The Nature Conservancy, San Francisco, California. 25 pages.
Williams, D.F., Cypher, E.A., Kelly, P.A., Norvell, N., Johnson, C.D., Colliver, G.W., and Miller, K.J. 1997. Recovery plan for upland species of the San Joaquin Valley, California. U.S. Fish and Wildlife Service, Portland, Oregon.

**Comment by cjlortie** [comment]
thank you for the detailed review on citations. I am sorry the ecosystem migration was NOT seamless.

**Comment by cjlortie** [comment]
OMG!!! forever.
