### ISSUE TITLE
Preparation for submission

### ISSUE THREAD

**Issue by cjlortie** [cjlortie/Strategic_retired_lands_synthesis#7]
- [x] research good fit journals including Am Midland Nat, Southwestern Naturalist, J of Arid Evnt, Perspectives, rangeland ecology and management, Ecology & Soc, Conservation & Society, Ambio, Biological Reviews
- [ ] write cover letter
- [x] remove all non-original figures
- [x] reduce word count (currently at 21,979 words most journals limit at 8000)
- [x] format for journal
- [ ] publish data and cite directly in the paper
- [x] connect to Mendeley
- [x] Error check all citations
- [ ] locate same reviews from target journals, check them, and cite one from the journal of choice

**Comment by cjlortie** [comment]
working on Ecosphere setup now.

**Comment by hscottbutterfield** [comment]
sounds great. spoke to abby yesterday. we are ready to review whenever you guys are done. no pressure from us. just don't want to hold up the process. thanks guys!

**Comment by cjlortie** [comment]
thanks.
not ready yet. still working with Ecosphere through instructions and a few clunky issues.

**Comment by cjlortie** [comment]
publish data
publish code
add citations to both in ms

**Comment by cjlortie** [comment]
Land Degradation & Development
Science of the Total Environment

**Comment by cjlortie** [comment]
alt title: when opportunity knocks:

**Comment by cjlortie** [comment]
Abigail K. Hart in the manuscript.

**Comment by afilazzola** [comment]
Same for me please:
Alessandro Filazzola

**Comment by cjlortie** [comment]
lol, all good team.
